
[package]
name = "sportblocks_nft"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.5.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
exit_first = true

[profile.dev.sierra]
replace_ids = true
